# Generated by Django 5.2 on 2025-05-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('notes', '0008_remove_notes_views_count_notes_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bookmark',
            field=models.ManyToManyField(related_name='User', to='notes.notes'),
        ),
    ]
