# Generated by Django 5.2 on 2025-04-24 21:22

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(upload_to='user_profile_image', blank=True, null=True),
        )

    ]
