# Generated by Django 5.2 on 2025-05-12 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_bookmark'),
        ('notes', '0008_remove_notes_views_count_notes_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='follow',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='bookmark',
            field=models.ManyToManyField(related_name='bookmark', to='notes.notes'),
        ),
    ]
