# Generated by Django 5.2 on 2025-04-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250425_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='social_links',
        ),
    ]
