# Generated by Django 5.2 on 2025-05-12 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_users_follow_alter_users_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='follow',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
