# Generated by Django 5.2 on 2025-05-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_users_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_user.png', null=True, upload_to='user_profile_image'),
        ),
    ]
