# Generated by Django 5.2 on 2025-05-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_users_profile_image'),
        ('notes', '0009_alter_notes_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='like',
            field=models.ManyToManyField(related_name='liked', to='notes.notes'),
        ),
    ]
