# Generated by Django 5.2 on 2025-07-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_user_secqo4.png', null=True, upload_to='user_profile_image'),
        ),
    ]
