# Generated by Django 5.2 on 2025-07-06 18:17

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_users_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_user_secqo4.png', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='user_profile_image'),
        ),
    ]
