# Generated by Django 5.2 on 2025-04-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='tag',
            field=models.ManyToManyField(related_name='Notes', to='notes.tags'),
        ),
    ]
