# Generated by Django 5.2 on 2025-04-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notes_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
