# Generated by Django 5.2 on 2025-04-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notes_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='private',
            new_name='public',
        ),
    ]
