# Generated by Django 5.2 on 2025-04-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_rename_private_notes_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='user_id',
            new_name='auther',
        ),
        migrations.AlterField(
            model_name='notes',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
