# Generated by Django 5.2 on 2025-04-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_rename_user_id_notes_auther_alter_notes_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='auther',
            new_name='author',
        ),
    ]
