# Generated by Django 5.2 on 2025-05-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_remove_notes_views_count_notes_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_image',
            field=models.ImageField(blank=True, default='default_note_image.png', null=True, upload_to='note_image'),
        ),
    ]
