# Generated by Django 5.2 on 2025-07-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_alter_notes_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_image',
            field=models.ImageField(blank=True, default='note_default_l1oecm.png', null=True, upload_to='note_image'),
        ),
    ]
