# Generated by Django 5.2 on 2025-07-06 18:17

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_alter_notes_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_image',
            field=models.ImageField(blank=True, default='note_default_l1oecm.png', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='note_image'),
        ),
    ]
